# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

# Defaults
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default
# https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Custom_Keybindings.md

git:
  pagers:
    - # https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md#delta
      colorArg: always
      pager: delta --dark --paging=never
  mainBranches:
    - master
    - main
    - develop
keybinding:
  universal:
    prevItem: u
    nextItem: e
    edit: I
  status:
    checkForUpdate: ''
gui:
  nerdFontsVersion: "3"
  showCommandLog: false
customCommands:
  - key: "U"
    description: "Update submodules"
    command: "git submodule update --init --recursive"
    context: "global"
    loadingText: "Updating submodules..."
    output: log
